apiVersion: v1
kind: ConfigMap
metadata:
  name: test-ms-tester-01-base
  labels:
    app: test-ms-tester-01-base
data:
  log.level: info
  service.name: "test-ms-tester-01-base"
  service.basePath: "/"
  service.version: "v1"