apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-ms-tester-01-base
  labels:
    app: test-ms-tester-01-base
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-ms-tester-01-base
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: test-ms-tester-01-base
    spec:
      containers:
        - name: test-ms-tester-01-base
          image: nginx:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "0.1"
              memory: 128Mi
          envFrom:
            - configmapRef: test-ms-tester-01-base