apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ values.name }}-${{ values.owner }}-01-base
  labels:
    app: ${{ values.name }}-${{ values.owner }}-01-base
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{ values.name }}-${{ values.owner }}-01-base
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ${{ values.name }}-${{ values.owner }}-01-base
    spec:
      containers:
        - name: ${{ values.name }}-${{ values.owner }}-01-base
          image: containerregistrymsshawe.azurecr.io/${{ values.name }}-${{ values.owner }}-01-base:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "0.1"
              memory: 128Mi
          envFrom:
            - configmapRef: ${{ values.name }}-${{ values.owner }}-01-base