apiVersion: v1
kind: Service
metadata:
  name: test-ms-tester-01-base
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: test-ms-tester-01-base
  ports:
    - port: 3000
      targetPort: 3000