apiVersion: v1
kind: Service
metadata:
  name: ${{ values.name }}-${{ values.owner }}-01-base
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: ${{ values.name }}-${{ values.owner }}-01-base
  ports:
    - port: 3000
      targetPort: 3000